export const DISTRITOS = [
  { id: "1", nombre: "CHACHAPOYAS" },
  { id: "2", nombre: "ASUNCIÓN" },
  { id: "3", nombre: "BALSAS" },
  { id: "4", nombre: "CHAUCHA" },
  { id: "5", nombre: "CHILIQUÍN" },
  { id: "6", nombre: "CHUQUIBAMBA" },
  { id: "7", nombre: "GRANADA" },
  { id: "8", nombre: "HUANCAS" },
  { id: "9", nombre: "LA JALCA" },
  { id: "10", nombre: "LEIMEBAMBA" },
  { id: "11", nombre: "LEVANTO" },
  { id: "12", nombre: "MAGDALENA" },
  { id: "13", nombre: "MARISCAL CASTILLA" },
  { id: "14", nombre: "MOLINOPAMPA" },
  { id: "15", nombre: "MONTEVIDEO" },
  { id: "16", nombre: "OLLEROS" },
  { id: "17", nombre: "QUINJALCA" },
  { id: "18", nombre: "SAN FRANCISCO DE DAGUAS" },
  { id: "19", nombre: "SAN ISIDRO DE MAINO" },
  { id: "20", nombre: "SOLOCO" },
];
