export const DISTRITOS = [
  { id: "1", nombre: "Ica" },
  { id: "2", nombre: "La Tinguiña" },
  { id: "3", nombre: "Los Aquijes" },
  { id: "4", nombre: "Ocucaje" },
  { id: "5", nombre: "Pachacútec" },
  { id: "6", nombre: "Parcona" },
  { id: "7", nombre: "Pueblo Nuevo" },
  { id: "8", nombre: "Salas" },
  { id: "9", nombre: "San José de Los Molinos" },
  { id: "10", nombre: "San Juan Bautista" },
  { id: "11", nombre: "Santiago" },
  { id: "12", nombre: "Subtanjalla" },
  { id: "13", nombre: "Tate" },
  { id: "14", nombre: "Yauca del Rosario" },
];
